platform :ios, '9.0'
target 'ZCLanguageDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod 'AFNetworking', '~> 3.2.0'

end
